[versions]
activityKtx = "1.11.0"
coordinatorlayout = "1.3.0"
core = "1.7.0"
desugar_jdk_libs = "2.1.5"
firebaseBom = "34.5.0"
firebaseMessagingKtx = "24.1.2"
glide = "5.0.5"
googleHiltAndroidVersion = "2.57.2"
hiltCompiler = "2.57.2"
imagepicker = "2.1"
coreKtx = "1.17.0"
appcompat = "1.7.1"
junit = "4.13.2"
kotlinTestJunit = "1.8.0"
kotlinxCoroutinesPlayServices = "1.10.2"
lifecycleLivedataKtxVersion = "2.9.4"
lifecycleViewmodelKtxVersion = "2.9.4"
loggingInterceptorVersion = "5.3.0"
material = "1.13.0"
constraintlayout = "2.2.1"
navigationFragmentKtxVersion = "2.9.6"
navigationUiKtxVersion = "2.9.6"
pagingRuntimeKtx = "3.3.6"
playServicesBaseVersion = "18.9.0"
recyclerview = "1.4.0"
roomCompiler = "2.8.3"
roomPaging = "2.8.3"
roomRuntime = "2.8.3"
roomKtx = "2.8.3"
lifecycleRuntimeKtx = "2.9.4"
swiperefreshlayout = "1.1.0"
retrofit = "3.0.0"
retrofitConverterGson = "3.0.0"
coroutinesAndroid = "1.10.2"



[libraries]
androidx-activity-ktx = { module = "androidx.activity:activity-ktx", version.ref = "activityKtx" }
androidx-coordinatorlayout = { module = "androidx.coordinatorlayout:coordinatorlayout", version.ref = "coordinatorlayout" }
androidx-core = { module = "androidx.test:core", version.ref = "core" }
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
androidx-lifecycle-livedata-ktx-v291 = { module = "androidx.lifecycle:lifecycle-livedata-ktx", version.ref = "lifecycleLivedataKtxVersion" }
androidx-lifecycle-runtime-ktx = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
androidx-lifecycle-viewmodel-ktx-v291 = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "lifecycleViewmodelKtxVersion" }
androidx-navigation-fragment-ktx-v290 = { module = "androidx.navigation:navigation-fragment-ktx", version.ref = "navigationFragmentKtxVersion" }
androidx-navigation-ui-ktx-v290 = { module = "androidx.navigation:navigation-ui-ktx", version.ref = "navigationUiKtxVersion" }
androidx-paging-runtime-ktx = { module = "androidx.paging:paging-runtime-ktx", version.ref = "pagingRuntimeKtx" }
androidx-room-compiler-v250 = { module = "androidx.room:room-compiler", version.ref = "roomCompiler" }
androidx-room-ktx = { module = "androidx.room:room-ktx", version.ref = "roomKtx" }
androidx-room-paging = { module = "androidx.room:room-paging", version.ref = "roomPaging" }
androidx-swiperefreshlayout = { module = "androidx.swiperefreshlayout:swiperefreshlayout", version.ref = "swiperefreshlayout" }
converter-gson = { module = "com.squareup.retrofit2:converter-gson", version.ref = "retrofitConverterGson" }
desugar_jdk_libs = { module = "com.android.tools:desugar_jdk_libs", version.ref = "desugar_jdk_libs" }
glide = { module = "com.github.bumptech.glide:glide", version.ref = "glide" }
google-firebase-bom = { module = "com.google.firebase:firebase-bom", version.ref = "firebaseBom" }
google-firebase-messaging-ktx = { module = "com.google.firebase:firebase-messaging-ktx", version.ref = "firebaseMessagingKtx" }
hilt-android-v2562 = { module = "com.google.dagger:hilt-android", version.ref = "googleHiltAndroidVersion" }
hilt-compiler = { module = "com.google.dagger:hilt-compiler", version.ref = "hiltCompiler" }
imagepicker = { module = "com.github.dhaval2404:imagepicker", version.ref = "imagepicker" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
junit = { module = "junit:junit", version.ref = "junit" }
kotlin-test-junit = { module = "org.jetbrains.kotlin:kotlin-test-junit", version.ref = "kotlinTestJunit" }
kotlinx-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "coroutinesAndroid" }
kotlinx-coroutines-play-services = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-play-services", version.ref = "kotlinxCoroutinesPlayServices" }
logging-interceptor-v4120 = { module = "com.squareup.okhttp3:logging-interceptor", version.ref = "loggingInterceptorVersion" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
androidx-constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
androidx-recyclerview = { group = "androidx.recyclerview", name = "recyclerview", version.ref = "recyclerview" }
play-services-base-v1870 = { module = "com.google.android.gms:play-services-base", version.ref = "playServicesBaseVersion" }
retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }
room-runtime = { module = "androidx.room:room-runtime", version.ref = "roomRuntime" }


[plugins]
#android-application = { id = "com.android.application", version.ref = "agp" }
#jetbrains-kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
#android-library = { id = "com.android.library", version.ref = "androidLibrary" }
#google-gms-google-services = { id = "com.google.gms.google-services", version.ref = "googleServices" }
#jetbrains-kotlin-kapt = { id = "org.jetbrains.kotlin.kapt" }
#devtools-ksp = { id = "com.google.devtools.ksp", version.ref = "devtoolsKsp" }
#hilt-android = { id = "com.google.dagger.hilt.android", version.ref = "googleHiltAndroidVersion" }
